import Header from '../components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import FooterNav from '../components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col items-center justify-between bg-blue-500 ${inter.className}`}>
    <Header />
      <main className="flex-1 bg-orange-500 w-full flex flex-col items-center justify-around">
      {children}
  </main>
       <FooterNav/>
        </body>
    </html>
  )
}
